# Generated by Django 5.2.4 on 2025-07-20 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("artists", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Artwork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=64, verbose_name="작품명")),
                (
                    "size_width",
                    models.DecimalField(
                        decimal_places=1, max_digits=6, verbose_name="가로(cm)"
                    ),
                ),
                (
                    "size_height",
                    models.DecimalField(
                        decimal_places=1, max_digits=6, verbose_name="세로(cm)"
                    ),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True, max_length=500, null=True, verbose_name="이미지 URL"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        max_digits=10,
                        null=True,
                        verbose_name="가격",
                    ),
                ),
                ("canvas_size", models.IntegerField(default=10, verbose_name="호수")),
                ("creation_year", models.IntegerField(verbose_name="제작년도")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록일"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artworks",
                        to="artists.artist",
                        verbose_name="작가",
                    ),
                ),
            ],
            options={
                "verbose_name": "작품",
                "verbose_name_plural": "작품들",
                "db_table": "artworks",
                "ordering": ["-created_at"],
            },
        ),
    ]
