# Generated by Django 5.2.4 on 2025-07-20 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("artists", "0001_initial"),
        ("artworks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exhibition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=64, verbose_name="전시명")),
                ("start_date", models.DateField(verbose_name="시작일")),
                ("end_date", models.DateField(verbose_name="종료일")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="등록일"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exhibitions",
                        to="artists.artist",
                        verbose_name="참여 작가",
                    ),
                ),
            ],
            options={
                "verbose_name": "전시",
                "verbose_name_plural": "전시들",
                "db_table": "exhibitions",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="ExhibitionArtwork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "artwork",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="artworks.artwork",
                    ),
                ),
                (
                    "exhibition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="exhibitions.exhibition",
                    ),
                ),
            ],
            options={
                "verbose_name": "전시 작품",
                "verbose_name_plural": "전시 작품들",
                "db_table": "exhibition_artworks",
                "unique_together": {("exhibition", "artwork")},
            },
        ),
        migrations.AddField(
            model_name="exhibition",
            name="artworks",
            field=models.ManyToManyField(
                blank=True,
                related_name="exhibitions",
                through="exhibitions.ExhibitionArtwork",
                to="artworks.artwork",
                verbose_name="전시 작품",
            ),
        ),
        migrations.AddIndex(
            model_name="exhibition",
            index=models.Index(
                fields=["start_date"], name="exhibitions_start_d_86286f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="exhibition",
            index=models.Index(
                fields=["end_date"], name="exhibitions_end_dat_fd396e_idx"
            ),
        ),
    ]
