# Generated by Django 5.2.4 on 2025-07-20 15:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("artist_name", models.CharField(max_length=16, verbose_name="작가명")),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "남자"), ("female", "여자")],
                        default="male",
                        max_length=10,
                        verbose_name="성별",
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(max_length=254, verbose_name="연락용 이메일"),
                ),
                (
                    "approved_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="승인일"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="사용자",
                    ),
                ),
            ],
            options={
                "verbose_name": "작가",
                "verbose_name_plural": "작가들",
                "db_table": "artists",
                "ordering": ["-approved_at"],
            },
        ),
        migrations.CreateModel(
            name="ArtistApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(max_length=20, verbose_name="연락처")),
                ("birth_date", models.DateField(verbose_name="생년월일")),
                ("artist_name", models.CharField(max_length=16, verbose_name="작가명")),
                (
                    "gender",
                    models.CharField(
                        choices=[("male", "남자"), ("female", "여자")],
                        default="male",
                        max_length=10,
                        verbose_name="성별",
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(max_length=254, verbose_name="연락용 이메일"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "심사 중"),
                            ("approved", "승인"),
                            ("rejected", "반려"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="심사 상태",
                    ),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="심사일"),
                ),
                (
                    "applied_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="신청일"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="신청자",
                    ),
                ),
            ],
            options={
                "verbose_name": "작가 신청",
                "verbose_name_plural": "작가 신청들",
                "db_table": "artist_applications",
                "ordering": ["-applied_at"],
            },
        ),
    ]
